version: '3.8'

services:
  hsb-ui:
    build: .
    container_name: hsb-ui
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: unless-stopped
    networks:
        - nginx-network
    # Use the dockeradmin user ID from the host system
    user: "${UID:-1000}:${GID:-1000}"

networks:
  nginx-network:
    external: true
    name: nginx-proxy
